actions:
  open-firefox:
    label: Open Firefox
    description: Open new firefox tab
    type: Runner
    color: red
    exec: firefox -new-tab about:blank

  open-slack:
    label: Open Slack
    description: Slack ready to chat
    type: Activate
    color: lightblue
    exec: slack
    shortcut: ctrl_k

  open-rdstation:
    label: 'Open Production App'
    description: Open RD Station Marketing
    type: Runner
    color: default
    exec: firefox -new-tab https://app.rdstation.com.br

  open-dev-rdstation:
    label: 'Open Devel App'
    description: Open RD Station Marketing (devel)
    type: Runner
    color: default
    exec: firefox -new-tab http://localhost:3000

  jarillaz-pull-requests:
    label: GitHub Pull Requests
    description: Open GitHub Pull Requests
    type: Runner
    color: lightblue
    exec: firefox -new-tab "https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3Advinciguerra+archived%3Afalse+sort%3Aupdated-desc"

  type-lorem:
    label: Type Lorem
    description: Type a lorem ipsum
    type: Typer
    color: yellow
    exec: Lorem ipsum dolor sit amet

